### PR TITLE
WIP: fix the build

### PR DESCRIPTION
**Pull request by naartjie**

### CODE REVIEW

**Comment by haraldsteinlechner** [comment]
CI is still failing because of missing chmod +x?

**Comment by haraldsteinlechner** [comment]
but your other PR fixes the problem, right?

**Comment by naartjie** [comment]
@haraldsteinlechner I created #33 just to check, and it is green:

https://ci.appveyor.com/project/stefanmaierhofer/aardvark-docs/builds/35447824
Screenshot 2020-09-28 at 16 57 07

**Comment by haraldsteinlechner** [comment]
cool. i think both of your pr's in combo fixed it :)

Marcin Jekot <notifications@github.com> schrieb am Mo., 28. Sep. 2020,
18:00:

**Comment by naartjie** [comment]
Indeed, I meant to chmod +x in this one, but my 2 PR's got intertwined somehow

**Comment by haraldsteinlechner** [comment]
i suspected this, that is why i merged both. thanks

Marcin Jekot <notifications@github.com> schrieb am Mo., 28. Sep. 2020,
18:05:

**Pull request merged**
